version: "3"
services:
  jupyter:
    container_name: "numerai"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: "Asia/Tokyo"
    env_file:
      - .env
    volumes:
      - .:/workspace:cached
    ports:
      - 8880:8880
    command: "jupyter lab --ip=0.0.0.0 --allow-root --NotebookApp.token='' --port=8880 --no-browser"
